---
- name: determine number of db hosts
  set_fact: num_db_hosts="{{ groups['mysql_hosts'] | length }}"
  tags:
    - extra_steps

- name: set mysql_master_ip
  set_fact: mysql_master_ip={{ (num_db_hosts | int == 0) | ternary("{{ hostvars[groups['primary_cs_manager'][0]]['ansible_ssh_host'] }}","{{ hostvars[groups['mysql_master_host'][0]]['ansible_ssh_host'] }}") }}
  tags:
    - extra_steps

- name: get upgrade version facts
  cs_version_facts:
    versionstring: "{{ upgrade_cloudstack_ver }}"
    isupgrade: true
  register: cs_upgrade_data

- debug: msg="upgrade_cs_subminor_version {{ upgrade_cs_subminor_version }}"
  
- debug: msg="upgrade_cs_minor_version {{ upgrade_cs_minor_version }}"

- debug: msg="old_cs_minor_version {{ old_cs_minor_version }}"

- name: copy upgrade script to mgmt.
  block:
    - copy:
        src: "{{ inventory_dir }}/roles/cloudstack-manager/files/update_db_410_to_411.sql"
        dest: /tmp/update_db_410_to_411.sql
    - shell: "mysql -h'{{ mysql_master_ip }}' -u'root' -p{{ mysql_root_password }} < /tmp/update_db_410_to_411.sql"
  when: upgrade_cs_subminor_version is version('4.11.0', '==') and old_cs_minor_version is version('4.10', '==')


- name: preset some global settings
  acs_mysql_update: DBHOST="{{ mysql_master_ip }}" DBUSER="cloud" DBPASS={{ mysql_cloud_password }} MYSQL_STATEMENT="UPDATE cloud.configuration SET value='8096' WHERE name='integration.api.port';"

- name: reload cloudstack.unit
  shell: systemctl daemon-reload
  when: upgrade_cs_minor_version is version('4.11','==')
  tags:
    - extra_steps