---

- name: Ensure selinux python bindings are installed
  yum: name=libselinux-python state=present

- name: CentOS 7 hostname fixup
  file: path=/etc/hostname state=absent
  when: ansible_distribution_major_version == "7"

- name: ensure yum cache is cleared
  shell: command="yum clean all"

- name: Set selinux to permissive
  command: setenforce permissive
  changed_when: false

- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive

- name: Ensure CA Certs are latest
  yum: name=ca-certificates state=latest enablerepo=base

- name: Ensure EPEL is available (centOS6)
  yum: name="{{ epel6 }}" state=present
  ignore_errors: true
  when: ansible_distribution_major_version == "6"

- name: Ensure EPEL is available (centOS7)
  yum: name="{{ epel7 }}" state=present
  ignore_errors: true
  when: ansible_distribution_major_version == "7"

- name: switch to baseurl as mirrors seem unreliable
  shell: sed -i -e 's|mirrorlist=https:|#mirrorlist=http:|g' -e 's|#baseurl=http|baseurl=http|g' /etc/yum.repos.d/epel.repo

- name: update lvm2 as fix for bugzilla.redhat.com/show_bug.cgi?id=1294128
  yum: name=lvm2 state=latest

- debug: msg="Set Java on VM"
- set_fact: java_ver="{{ mgmt_java_ver }}"
- set_fact: java_path="{{ mgmt_java_path }}"
- include: ../../../tasks/set_java.yml
  when: force_java

- include: ./centos-acs.yml
  when: ("{{ env_version[0:2]}}" == "cs")

- include: ./centos-ccp.yml
  when: ("{{ env_version[0:3]}}" == "ccp")

- name: ensure rpcbind in started
  service: name=rpcbind state=started enabled=yes

- name: copy cloudutil script to /usr/bin
  copy: src=cloudutil dest=/usr/bin/ mode=0755

- debug: msg="Some Marvin Stuff"
  when: (num_marv_hosts > 0)

- name: Ensure sshpass is installed (CentOS 7)
  yum: name=sshpass state=present
  when: (num_marv_hosts > 0)

- name: Open 8096 when Marvin is required (CentOS 6)
  shell: "iptables -I INPUT -p tcp -m tcp --dport 8096 -j ACCEPT && iptables-save > /etc/sysconfig/iptables"
  when: (num_marv_hosts > 0)
# and (ansible_distribution_major_version == "6")

#- name: Open 8096 when Marvin is required (CentOS 7)
#  shell: firewall-cmd --permanent --zone=public --add-port=8096/tcp && firewall-cmd --reload
#  when: (num_marv_hosts > 0) and (ansible_distribution_major_version == "7")
