---

- name: stop services
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - cloudstack-management
    - cloudstack-usage

# set upgrade repo 'fact'
- set_fact:
    baseurl_cloudstack: "{{ upgrade_baseurl_mgmt }}"

- debug:
    msg: "{{baseurl_cloudstack}}"
- name: update cloudstack repo
  template:
    src: "{{ inventory_dir }}/roles/cloudstack-manager/templates/cloudstack.repo.j2"
    dest: /etc/yum.repos.d/cloudstack.repo

- name: upgrade cloudstack binaries
  yum:
    name: cloudstack-*
    state: latest

- name: Perform any additional pre-restart upgrade steps
  include: additional_pre-restart_upgrade_steps.yaml
  run_once: yes

- name: start services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - cloudstack-management
    - cloudstack-usage

- name: Perform any additional post-restart upgrade steps
  include: additional_post-restart_upgrade_steps.yaml

