---

- name: get pre-upgrade CloudStack version from server
  shell: "cloudmonkey list capabilities | jq -r '.capability[] | .cloudstackversion'"
  register: CloudStack_original_version

- name: set get original version vars
  cs_version_facts:
    versionstring: "cs{{ CloudStack_original_version }}"
    isupgrade: false
  register: cs_orginal_version

- name: stop services
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - cloudstack-management
    - cloudstack-usage

- name: determine number of db hosts
  set_fact: num_db_hosts="{{ groups['mysql_hosts'] | length }}"

- name: set mysql_master_ip
  set_fact: mysql_master_ip={{ (num_db_hosts | int == 0) | ternary("{{ hostvars[groups['primary_cs_manager'][0]]['ansible_ssh_host'] }}","{{ hostvars[groups['mysql_master_host'][0]]['ansible_ssh_host'] }}") }}

- name: backup database
  shell: mysqldump -h'{{ mysql_master_ip }}' -u'root' -p{{ mysql_root_password }} --databases cloud cloud_usage > /root/db_backup.sql

- debug:
    msg: "{{upgrade_baseurl_mgmt}}"

# set upgrade repo 'fact'
- set_fact:
    baseurl_cloudstack: "{{ upgrade_baseurl_mgmt }}"

- name: update cloudstack repo
  template:
    src: "{{ inventory_dir }}/roles/cloudstack-manager/templates/cloudstack.repo.j2"
    dest: /etc/yum.repos.d/cloudstack.repo

- name: upgrade cloudstack binaries
  yum:
    name: "cloudstack-management-{{ upgrade_cs_numeric_version }}"
    state: latest

- name: Perform any additional pre-restart upgrade steps
  vars: 
    - env_cs_minor_version: "{{ env_cs_minor_version }}"
  include: additional_pre-restart_upgrade_steps.yaml
  run_once: yes

- name: start services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - cloudstack-management
    - cloudstack-usage

- name: Perform any additional post-restart upgrade steps
  include: additional_post-restart_upgrade_steps.yaml

