
#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.



---
- name: Ensure the Apache Cloudstack Repo file is configured (CentOS 6)
  template: src=cloudstack.repo.j2 dest=/etc/yum.repos.d/cloudstack.repo
  when: ansible_distribution_major_version == "6"

- name: Ensure the Apache Cloudstack Repo file is configured (CentOS 7)
  template: src=cloudstack.repo_centos7.j2 dest=/etc/yum.repos.d/cloudstack.repo
  when: ansible_distribution_major_version == "7"

- name: Ensure CloudStack packages are installed
  yum: name=cloudstack-agent state=present
  tags:
    - kvm
    - kvm-agent

- name: Bugfix libvirt cpu issue on ACS 4.5 (CLOUDSTACK-8443)
  shell: sed -i -e '/cgroup\_controllers/d' /usr/lib64/python2.7/site-packages/cloudutils/serviceConfig.py
  when: ansible_distribution_major_version == "7"
  tags:
    - kvm
    - kvm-agent

- name: KVM libvirtd restarted
  service: name=libvirtd state=restarted
  tags:
    - kvm
    - kvm-agent