---


- name: Request and return environment details
  env_db_manage: DBHOST={{ env_db_ip }} DBUSER={{ env_db_user }} DBPASS={{ env_db_password }} DBNAME={{ env_db_name }} ENV_UUID={{ env_uuid }} ENV_NAME={{ env_name_clean }} ENV_ZONETYPE={{ env_zonetype }} ENV_ACTION=retrieve
  register: env_ranges
  tags:
    - buildzone
    - create_script

- debug: msg="{{ env_ranges }}"
  tags:
    - buildzone
    - create_script

- name: Copy Cloudmonkey zone create script to mgmt server
  template: src="deployzone.sh.j2" dest="/tmp/deployzone.sh" mode=0744
  tags:
    - buildzone
    - create_script
