---

#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

####################################################################
# Set delete / expunge for VMs. Can not be accomplished with
# the CloudStack Ansible modules hence using cs commands.
#

####################################################################
# Remove servers
#
- name: Set remove action
  set_fact: vm_state="expunged"
  when: expunge is defined

- name: remove  hosts
  local_action:
    module: cs_instance
    name: "{{ item }}"
    project: "{{ build_project }}"
    state: "{{ vm_state | default( 'absent' ) }}"
    force: true
  with_items:
    - "{{ groups['vc_hosts'] }}"
    - "{{ groups['hypervisor_hosts'] }}"
    - "{{ groups['mysql_hosts'] }}"
    - "{{ groups['cloudstack_manager_hosts'] }}"
  register: remove_retval

- name: Update inventory file - remove server IP addresses
  replace:
    dest="hosts_{{ env_name_clean }}"
    regexp='{{ item.default_ip }}'
    replace='{{ item.name }}-ip'
    backup=no
  with_items: "{{remove_retval.results}}"

- name: Remove HV IP list from group vars
  lineinfile:
    dest="group_vars/{{ env_name_clean }}"
    regexp="^env_hviplist.*$"
    state=absent

####################################################################
# Remove environment files
#
- name: Delete inventory files
  file:
    path="{{ item }}"
    state="absent"
  with_items:
    - "hosts_{{ env_name_clean }}"
    - "group_vars/{{ env_name_clean }}"
  when: removeconfig is defined

####################################################################
# Remove project
#
- name: Delete project
  local_action:
    module: cs_project
    name: "{{ build_project }}"
    state: absent
  when: removeproject is defined

####################################################################
# Remove Environment IP range
#
- name: copy the environment delete script first
  copy: src=templates/enviroment_remove.sh.j2 dest=/tmp/{{ env_name_clean }}_enviroment_remove.sh mode=0744

- name: Environment remove script
  shell: "/tmp/{{ env_name_clean }}_enviroment_remove.sh -e {{ env_name_clean }} -n {{ hostvars[groups['primary_storage_hosts'][0]]['ansible_ssh_host'] }} -m {{ hostvars[groups['secondary_storage_hosts'][0]]['ansible_ssh_host'] }} -r '{{ env_pripath }}' -s '{{ env_secpath }}'"
