---

- debug: msg="clusterid={{ lowestclusterid }} vmid={{ item.id }}"

- name: Get least used host
  custom_allocator: 
    algorithm: least_host_in_cluster
    clusterid: "{{ lowestclusterid }}"
  register: allocator_output

- debug:
    msg: "{{ allocator_output }}"
      

- name: Start VM
  shell: "cs startVirtualMachine id={{ item.id }} hostid={{ allocator_host_id }}"
