---

- debug: msg="Java version required is {{ java_ver }}"

- name: ensure that above Java version is present
  yum: name="{{ java_ver }}" state=latest enablerepo=base
#  when: ("{{ java_type}}" == "openjdk")

- debug: msg="register oracle java with alternatives (TODO)"

- name: "set {{ java_ver }} as default version - NOTE: This will appear to fail is already default"
  shell: "alternatives --set java `alternatives --list | grep {{ java_path }} | awk -F ' ' '{print $NF}'`"
  ignore_errors: yes
