---

- name: Ensure prerequisite libselinux-python installed
  yum: name=libselinux-python state=installed
  tags:
    - kvm

- name: CentOS 7 hostname fixup
  file: path=/etc/hostname state=absent
  when: ansible_distribution_major_version == "7"
  tags:
    - kvm

- name: Set selinux to permissive
  command: setenforce permissive
  changed_when: false
  tags:
    - kvm

- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive
  tags:
    - kvm

- name: Ensure EPEL is available
  yum: name="{{ epel6 }}" state=present
  when: ansible_distribution_major_version == "6"
  tags:
    - kvm

- name: Ensure EPEL is available
  yum: name="{{ epel7 }}" state=present
  when: ansible_distribution_major_version == "7"
  tags:
    - kvm

- name: switch to http for file mirrors
  shell: sed -i 's|mirrorlist=https:|mirrorlist=http:|g' /etc/yum.repos.d/epel.repo
  ignore_errors: true
  tags:
    - kvm

- name: Install basic utilities and tools
  yum: name={{ item }} state=present enablerepo=base
  with_items:
    - bind-utils
    - bridge-utils
    - ntp
    - openssh-clients
    - pciutils
    - telnet
    - tcpdump
    - traceroute
    - nano
    - iftop
    - python-argparse
  tags:
    - kvm

- include: ./kvm_networking.yml

- debug: msg="Set Java on VM"
- set_fact: java_ver="{{ kvm_java_ver }}"
- set_fact: java_path="{{ kvm_java_path }}"
- include: ../../../tasks/set_java.yml

- include: ./centos-acs.yml
  when: ("{{ env_version[0:2]}}" == "cs")

- include: ./centos-ccp.yml
  when: ("{{ env_version[0:3]}}" == "ccp")

- name: Update libvirtd.conf - listen_tls
  lineinfile: dest=/etc/libvirt/libvirtd.conf regexp={{ item.regexp }} line={{ item.line }}  state=present
  with_items:
    - { regexp: "listen_tls", line: "listen_tls = 0" }
    - { regexp: "listen_tcp", line: "listen_tcp = 1" }
    - { regexp: "tcp_port", line: "tcp_port = \"16509\"" }
    - { regexp: "auth_tcp", line: "auth_tcp = \"none\"" }
    - { regexp: "mdns_adv", line: "mdns_adv = 0" }
  tags:
    - kvm
    - kvm-agent

- name: Update /etc/sysconfig/libvirtd - LIBVIRTD_ARGS
  lineinfile: dest=/etc/sysconfig/libvirtd regexp='LIBVIRTD_ARGS' line='LIBVIRTD_ARGS="--listen"' state=present
  tags:
    - kvm
    - kvm-agent

- name: Update /etc/libvirt/qemu.conf
  lineinfile: dest=/etc/libvirt/qemu.conf regexp='vnc_listen' line='vnc_listen = "0.0.0.0"' state=present
  tags:
    - kvm
    - kvm-agent

- name: Bugfix libvirt cpu issue on ACS 4.5 (CLOUDSTACK-8443)
  shell: sed -i -e '/cgroup\_controllers/d' /usr/lib64/python2.7/site-packages/cloudutils/serviceConfig.py
  when: ansible_distribution_major_version == "7"
  tags:
    - kvm
    - kvm-agent

- name: Add iptables rules
  shell: "iptables -I INPUT -p tcp -m tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "22"
    - "1798"
    - "16509"
    - "5900:6100"
    - "49152:49216"
  tags:
    - kvm
    - kvm-agent

- name: IPtables save config
  shell: "iptables-save > /etc/sysconfig/iptables"
  tags:
    - kvm
    - kvm-agent

- name: KVM libvirtd restarted
  service: name=libvirtd state=restarted
  tags:
    - kvm
    - kvm-agent
