---

- name: wait for VM to be alive
  shell: "ping {{ ansible_ssh_host }} -c 1"
  register: pong
  until: pong.rc == 0
  retries: "{{ ssh_retries }}"
  
- name: Wait for SSH
  local_action: wait_for port=22 host="{{ ansible_ssh_host }}" timeout={{ ssh_retries }} connect_timeout=5

- name: install java
  yum: name: java-1.8.0-openjdk.x86_64 state=present

#- name: retrieve hipchat cli client dist
#  get_url: url="{{ marvin_cli_client_location }}" dest="/tmp/hipchapcli.zip"

- name: unpack files
  unarchive: src="{{ marvin_cli_client_location }}" dest=/tmp/hipchatcli/

- name: configure client  
  template: src="hipchat.sh.j2" dest="/tmp/hipchatcli/hipchat.sh" mode=0744

- name: create symlink to improve compatibility
  file: path=/usr/bin/hipchat src="/tmp/hipchatcli/hipchat.sh" state=link

